### ISSUE TITLE
How can I pass options to Uglify?

### ISSUE THREAD

**Issue by raphaelokon** [RReverser/babel-plugin-uglify#1]
Hi.

I would like to pass options to the CLI, like: `--compress --mangle` into this

``` bash
node_modules/.bin/babel src --out-file dist/lib.min.js --plugins uglify:after
```

Any clue how to achieve this?

**Comment by RReverser** [comment]
See https://github.com/babel/babel/issues/1833 for tracking issue for plugin options in Babel. Unfortunately, I can't do anything on my side until it's resolved.

**Comment by raphaelokon** [comment]
Cheers!

**Comment by PixnBits** [comment]
FWIW babel has migrated their issues, I believe the new URL is https://phabricator.babeljs.io/T1833

**Comment by RReverser** [comment]
@PixnBits It doesn't matter anymore due to #3
