### ISSUE TITLE
RegExp literal causes 'Invalid Literal type' error

### ISSUE THREAD

**Issue by dbaba** [RReverser/babel-plugin-uglify#2]
hi,
I encountered an unknown error when I ran babel with this plugin (`babel --plugins uglify:after test.js`.
Can you please address it?

```
Error: test.js: Invalid Literal type
    at CodeGenerator._Literal (/Users/foo/.nvm/versions/node/v0.12.7/lib/node_modules/babel/node_modules/babel-core/lib/generation/generators/types.js:180:15)
(snip)
```

And I identified what had caused the error.

```
console.log('NULL terminator is gone!\0'.replace(/\0/g, ''));
```

The regular expression `/\0/g`  caused the trouble.

The value was set to the variable `val` in [`_Literal(node)` function in `types.js`](https://github.com/mgcrea/babel-core/blob/master/lib/generation/generators/types.js#L180), which is a part of `babel-core` rather than this plugin.

Please tell me the right place if the issue is out of this plugin scope.

Module and Node versions:
- babel 5.8.23
- babel-plugin-uglify 1.0.2
- node js 0.12.7

**Comment by RReverser** [comment]
Hm, you pointed to some fork of `babel-core`. Please try to use original one.

If still happens, please post result of `uAST.to_mozilla_ast()`.

**Comment by skyne** [comment]
Can reporduce this with the original babel-core.

Here is the result of `uAST.to_mozilla_ast()`:

```
{"type":"Program","body":[{"type":"ExpressionStatement","expression":{"type":"Literal","value":"use strict"}},{"type":"ExpressionStatement","expression":{"type":"CallExpression","callee":{"type":"MemberExpression","object":{"type":"Literal","value":"NULL terminator is gone!\u0000","range":[0,28],"loc":{"start":{"line":1,"column":0},"end":{"line":1,"column":28},"source":"index.js"}},"computed":false,"property":{"type":"Identifier","name":"replace"},"range":[0,36],"loc":{"start":{"line":1,"column":0},"end":{"line":1,"column":36},"source":"index.js"}},"arguments":[{"type":"Literal","value":{},"range":[37,42],"loc":{"start":{"line":1,"column":37},"end":{"line":1,"column":42},"source":"index.js"}},{"type":"Literal","value":"","range":[44,46],"loc":{"start":{"line":1,"column":44},"end":{"line":1,"column":46},"source":"index.js"}}],"range":[0,47],"loc":{"start":{"line":1,"column":0},"end":{"line":1,"column":47},"source":"index.js"}},"range":[0,47],"loc":{"start":{"line":1,"column":0},"end":{"line":1,"column":47},"source":"index.js"}}],"range":[0,47],"loc":{"start":{"line":1,"column":0},"end":{"line":1,"column":47},"source":"index.js"}}
```

Here is the index.js:

```
'NULL terminator is gone!\0'.replace(/\0/g, '')
```

Here is my grunt file:

```
module.exports = function (grunt) {
    grunt.initConfig({
        babel: {
            options: {
                sourceMap: true
            },
            dist: {
                files: {
                    'dist/app.js': 'index.js'
                }
            }
        }
    });

    grunt.loadNpmTasks('grunt-babel');
    grunt.registerTask('default', ['babel']);
}
```

**Comment by RReverser** [comment]
This is the weird part in AST:

``` json
             {
                "type": "Literal",
                "value": {},
                "range": [37, 42],
                "loc": {
                    "start": {
                        "line": 1,
                        "column": 37
                    },
                    "end": {
                        "line": 1,
                        "column": 42
                    },
                    "source": "index.js"
                }
            }
```

Looks like AST is at some point being converted to JSON and so regexp object is lost and replaced with regular one.

**Comment by RReverser** [comment]
Are you sure you did just `console.log(uAST.to_mozilla_ast())` and didn't stringify it to JSON (which would be the reason of corruption)?

**Comment by SoonDead** [comment]
Yes the above one is JSON.stringified before logged to console.

But keep note that the JSON.stringified value was not used for anything, just for console output, so I don't think it would cause any corruption.

Here is the raw console.log output of the same:

```
{ type: 'Program',
  body:
   [ { type: 'ExpressionStatement', expression: [Object] },
     { type: 'ExpressionStatement',
       expression: [Object],
       range: [Object],
       loc: [Object] } ],
  range: [ 0, 47 ],
  loc:
   { start: { line: 1, column: 0 },
     end: { line: 1, column: 47 },
     source: 'index.js' }
}
```

**Comment by RReverser** [comment]
It did cause corruption of the log, so I can't tell anything from neither JSON.stringify'd nor collapsed version. Please show me full-depth log or just log specifically the node with regexp. All the other nodes look totally fine.

**Comment by SoonDead** [comment]
The result of `console.log(uAST.to_mozilla_ast().body[1].expression);`

```
{ type: 'CallExpression',
  callee:
   { type: 'MemberExpression',
     object:
      { type: 'Literal',
        value: 'NULL terminator is gone!\u0000',
        range: [Object],
        loc: [Object] },
     computed: false,
     property: { type: 'Identifier', name: 'replace' },
     range: [ 0, 36 ],
     loc: { start: [Object], end: [Object], source: 'index.js' } },
  arguments:
   [ { type: 'Literal', value: /\0/g, range: [Object], loc: [Object] },
     { type: 'Literal', value: '', range: [Object], loc: [Object] } ],
  range: [ 0, 47 ],
  loc:
   { start: { line: 1, column: 0 },
     end: { line: 1, column: 47 },
     source: 'index.js' } 
 }
```

**Comment by RReverser** [comment]
Ah well, apparently it's because Babel now expects `regex` to be defined for `Literal`s with regular expressions. Needs changes in UglifyJS AST conversion, please raise issue in their repo instead.

**Comment by dbaba** [comment]
The value `/\0/g` itself was a RegExp object rather than a string.

```
console.log(uAST.to_mozilla_ast().body[1].expression.arguments[0].value instanceof RegExp);
```

=> true

In addition, UglifyJS supports SpiderMonky AST and as long as I read the [SpiderMonkey Parser API doc](https://developer.mozilla.org/en-US/docs/Mozilla/Projects/SpiderMonkey/Parser_API), UglifyJS AST conversion was correct. There wasn't `regexp` property in `interface Literal` definition.

So I think the issue to be raised in babel. What do you think?

**Comment by RReverser** [comment]
SpiderMonkey API is long deprecated, I specifically added a note on top of that wiki page:

> NOTE: This page describes SpiderMonkey-specific behavior and might be incomplete. Visit ESTree spec for a community AST standard that includes latest ECMAScript features and is backward-compatible with SpiderMonkey format.

**Comment by SoonDead** [comment]
@RReverser I'm not really familiar with how uglify or babel works, so I'm struggling with writing a proper issue to babel. Can you please raise the issue?

**Comment by RReverser** [comment]
@SoonDead As I said - please raise an issue with UglifyJS not Babel, as it's support for ESTree is outdated and needs fix with adding such property.

**Comment by RReverser** [comment]
I can do that, but later and would be helpful if you would even migrate this issue as-is.

**Comment by dbaba** [comment]
Thanks. I filed a ticket in UglifyJS2 project as shown above.
Please add comments on the ticket if necessary as I don't have enough knowledge regarding the latest AST spec.

**Comment by RReverser** [comment]
Looks good to me, couldn't add more! :+1:
