### ISSUE TITLE
Error when used with Grunt-babel

### ISSUE THREAD

**Issue by ethyde** [RReverser/babel-plugin-uglify#6]
My grunt task work well whithout this plugin

```
// Grunt Babel JS task
babel: {
    options: {
        sourceMap: "inline",
        presets: ['es2015'],
        plugins: ["uglify:after"]
    },
    dev: {
        src: [ "<%= meta.dev.js %>/plugin/*.js",
            "<%= meta.dev.js %>/main.js"
        ],
        dest: "<%= meta.prod.js %>/main.js"
    }
}
```

But when i launch the task, i have this error..

```
Running "babel:dev" (babel) task
Warning: Unknown plugin "uglify:after" specified in "base" at 0, attempted to resolve relative to "dev/js" Use --force to continue.
```

**Comment by jlbruno** [comment]
Same issue in gulp. Is the plugin supported with these task runners?

**Comment by RReverser** [comment]
Plugins have nothing to do with task runners, as they just, um, run tasks :) From config I can tell that you're using Babel 6, which is currently unsupported (see https://github.com/RReverser/babel-plugin-uglify/pull/4#issuecomment-170895081).
